function band = loadbandfromdata(path_data, v0, ampl, freq, b, q)
    load(path_data, "name_dim", "quasienergy", ...
        "depth_latt", "max_shake", "freq_sweep", "bandidx", "qwv_norm", ...
        "grid_depth_latt", "grid_max_shake", "grid_freq_sweep", "grid_bandidx", "grid_qwv_norm");
    band = interpn( ...
        grid_depth_latt, grid_max_shake, grid_freq_sweep, grid_bandidx, grid_qwv_norm, ...
        quasienergy, v0, ampl, freq, b, q, "linear");
    band = squeeze(band); %- min(band(:));
end